name: Main Workflow

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  
jobs:
  determine-branch:
    runs-on: ubuntu-latest
    steps:

    - name: Configure Git Authentication
      run: |
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout Repo-A
      uses: actions/checkout@v3

    - name: Clone Repo-B
      run: git clone https://github.com/kolsgithub/github-action-importer-issueops.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
