name: Main Workflow
on:
  push:
    branches:
      - '**'
jobs:
  determine-branch:
    runs-on: ubuntu-latest
    outputs:
      branch-value: ${{ steps.set-output.outputs.branch-value }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Source Branch Name
        id: get-branch
        run: echo "Branch Name: ${{ github.ref_name }}"

      - name: Set Branch Value
        id: set-output
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "branch-value=production" >> $GITHUB_ENV
            echo "::set-output name=branch-value::production"
          else
            echo "branch-value=development" >> $GITHUB_ENV
            echo "::set-output name=branch-value::development"
          fi

  call-reusable-workflow:
    needs: determine-branch
    uses: ./.github/workflows/reusable.yml
    with:
      branch-value: ${{ needs.determine-branch.outputs.branch-value }}
