name: Reusable Workflow

on:
  workflow_call:
    inputs:
      branch-value:
        required: true
        type: string

jobs:
  process-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Log Branch Value
        run: echo "Branch Value: ${{ inputs.branch-value }}"
